version: '3'
services:
  web:
    build: .
    environment:
      - DEBUG=True
      - ALLOWED_HOST=*
      - SECRET_KEY=AFGcl457890liknoKpQOm42jwh
      - DB_HOST=postgres
      - DB_USER=prisma
      - DB_PASSWORD=prisma
      - OIDC_USERINFO_ENDPOINT=https://dev.account.gccollab.ca/openid/userinfo
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - image
  image:
    build: ./image-server
    volumes:
      - ./volumes/upload:/usr/share/nginx/html/upload
    environment:
      - TITLE=Meerkat-Image-Server
      - DOMAIN=https://avatar.gccollab.ca
      - LOWPROFILE=True
    ports:
    - "8007:80"
  yoga:
    build: ./
    image: profile-yoga
    environment: 
      NODE_ENV: "production"
      PRISMA_API_ENDPOINT: 'prisma'
    ports:
    - "4000:4000"
    depends_on: 
      - prisma
  prisma:
    image: prismagraphql/prisma:1.16
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: thehouseisalwaysblue
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./postgres:/var/lib/postgresql/data
